# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "concierge"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# log to a local file...
logger: file
#... and log EVERYTHING
log: core

# template engine
# simple: default and very basic template engine
# template_toolkit: TT
#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
   encoding:  'utf8'
#   start_tag: '[%'
#   end_tag:   '%]'

# listen on port 80 like a good little webapp should
#port: 80
#port: 8080
port: 80
